project_id = "wdowdibcidirhizpqiki"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[graphql]
enabled = true
port = 54323
db_schema = "public"
db_anon_role = "anon"
db_max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true
ip_version = 4
port = 54324

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
image_transformation = "enabled"

[auth]
enabled = true
port = 54329
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false

[functions.ai-query-enhancement]
verify_jwt = false