[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  JWT_SECRET_KEY = "turklawai-super-secret-jwt-key-2025-production-ready-authentication-system-v2"

# API routes to Netlify Functions
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/auth/health"
  status = 200
  force = true

# SPA fallback (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # Enable function bundling
  node_bundler = "esbuild"