// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdowdibcidirhizpqiki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indkb3dkaWJjaWRpcmhpenBxaWtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjI3OTYsImV4cCI6MjA2Nzg5ODc5Nn0.qV5gMR-bkAbRXpDu18PmgOziCQ0PEf3y6FWFet09FfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});